# Generated by Django 5.2.3 on 2025-06-19 15:22

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def add_data(apps, schema_editor):

    Utilisateur = apps.get_model('core', 'Utilisateur')
    Etudiant = apps.get_model('core', 'Etudiant')
    Prof = apps.get_model('core', 'Prof')
    Gestionnaire = apps.get_model('core', 'Gestionnaire')
    Classe = apps.get_model('core', 'Classe')
    Matiere = apps.get_model('core', 'Matiere')
    AnneeScolaire = apps.get_model('core', 'AnneeScolaire')
    Inscription = apps.get_model('core', 'Inscription')
    Type = apps.get_model('core', 'Type')
    Note = apps.get_model('core', 'Note')

    # Création des utilisateurs
    etu_user = Utilisateur.objects.create_user(first_name="Brahim", last_name="Diaz", username='etudiant', email='etu1@example.com', password='test', adresse='Rue Jbel Lakhdar, Marrakech')
    etu_user_1 = Utilisateur.objects.create_user(first_name="Lewis", last_name="Amilton", username='lwa', email='etud@example.com', password='test', adresse='67 Rue Birhakin Oasis, Casablance')
    etu_user_2 = Utilisateur.objects.create_user(first_name="Carlos", last_name="Sainz", username='carl', email='carlos@example.com', password='test', adresse='Rue Jbel Lakhdar, Marrakech')
    etu_user_3 = Utilisateur.objects.create_user(first_name="George", last_name="Russell", username='gr', email='george@example.com', password='test', adresse='Rue Jbel Lakhdar, Marrakech')
    etu_user_4 = Utilisateur.objects.create_user(first_name="Alberto", last_name="Contador", username='alc', email='alberto@example.com', password='test', adresse='67 Rue Birhakin Oasis, Casablance')
    etu_user_5 = Utilisateur.objects.create_user(first_name="Ahlam", last_name="Taourirt", username='ahlam', email='ahlam@example.com', password='test', adresse='67 Rue Birhakin Oasis, Casablance')
    etu_user_6 = Utilisateur.objects.create_user(first_name="Marc", last_name="Welberg", username='marc', email='marc@example.com', password='test', adresse='67 Rue Birhakin Oasis, Casablance')
    etu_user_7 = Utilisateur.objects.create_user(first_name="Micheal", last_name="Phelps", username='micheal', email='micheal@example.com', password='test', adresse='Place Nour El Kamar, Route De Casablanca, El Jadida')
    etu_user_8 = Utilisateur.objects.create_user(first_name="Valentino", last_name="Rossi", username='valentino', email='valentino@example.com', password='test', adresse='Place Nour El Kamar, Route De Casablanca, El Jadida')
    etu_user_9 = Utilisateur.objects.create_user(first_name="Sebastin", last_name="lobb", username='sebastin', email='sebastin@example.com', password='test', adresse='67 Rue Birhakin Oasis, Casablance')

    prof_user = Utilisateur.objects.create_user(first_name="Carlos", last_name="Alcaraz", username='prof1', email='prof1@example.com', password='test', adresse='Place Nour El Kamar, Route De Casablanca, El Jadida')
    prof_user1 = Utilisateur.objects.create_user(first_name="Max", last_name="Dupont", username='mdupont', email='mdupont@univ-exemple.com', password='test',adresse='53 boulevard Abdelmoumen, Casablanca')
    prof_user2 = Utilisateur.objects.create_user(first_name="Amin", last_name="Amine", username='amine', email='aamine@univ-exemple.com', password='test', adresse='45 rue papillon, Casablanca')
    prof_user3 = Utilisateur.objects.create_user(first_name="Mohamed", last_name="Moulay", username='moulay', email='mmoulay@univ-exemple.com', password='test', adresse='78 boulevard Massira, Casablanca')
    prof_user4 = Utilisateur.objects.create_user(first_name="Saber", last_name="Ayoub", username='ayoub', email='sayoub@univ-exemple.com', password='test', adresse='43 blvd Mohamed VI, Tanger')
    prof_user5 = Utilisateur.objects.create_user(first_name="Pep", last_name="Goardiola", username='pep', email='pep@univ-exemple.com', password='test', adresse='43 blvd Mohamed VI, Tanger')
    prof_user6 = Utilisateur.objects.create_user(first_name="Hector", last_name="Ramirez", username='hector', email='hector@univ-exemple.com', password='test', adresse='43 blvd Mohamed VI, Tanger')


    gest_user = Utilisateur.objects.create_user(first_name="Alphonse", last_name="Alphonse", username='alphonse', email='alphonse@example.com', password='alphonse', adresse='Adresse Gestionnaire', is_staff=True, is_superuser = True)
    # Création des rôles
    etudiant = Etudiant.objects.create(utilisateur=etu_user)
    etudiant_1 = Etudiant.objects.create(utilisateur=etu_user_1)
    etudiant_2 = Etudiant.objects.create(utilisateur=etu_user_2)
    etudiant_3 = Etudiant.objects.create(utilisateur=etu_user_3)
    etudiant_4 = Etudiant.objects.create(utilisateur=etu_user_4)
    etudiant_5 = Etudiant.objects.create(utilisateur=etu_user_5)
    etudiant_6 = Etudiant.objects.create(utilisateur=etu_user_6)
    etudiant_7 = Etudiant.objects.create(utilisateur=etu_user_7)
    etudiant_8 = Etudiant.objects.create(utilisateur=etu_user_8)
    etudiant_9 = Etudiant.objects.create(utilisateur=etu_user_9)

    prof = Prof.objects.create(utilisateur=prof_user)
    prof_1 = Prof.objects.create(utilisateur=prof_user1)
    prof_2 = Prof.objects.create(utilisateur=prof_user2)
    prof_3 = Prof.objects.create(utilisateur=prof_user3)
    prof_4 = Prof.objects.create(utilisateur=prof_user4)
    prof_5 = Prof.objects.create(utilisateur=prof_user5)
    prof_6 = Prof.objects.create(utilisateur=prof_user6)

    gestionnaire = Gestionnaire.objects.create(utilisateur=gest_user)

    # Classe
    classe = Classe.objects.create(nom='Licence 1')
    classe_2 = Classe.objects.create(nom='Licence 2')
    classe_3 = Classe.objects.create(nom='Licence 3')
    classe_4 = Classe.objects.create(nom='Master 1')
    classe_5 = Classe.objects.create(nom='Master 2')
    
    # Année scolaire
    annee = AnneeScolaire.objects.create(nom='2024-2025')
    annee_1 = AnneeScolaire.objects.create(nom='2023-2024')
    annee_2 = AnneeScolaire.objects.create(nom='2022-2023')
    annee_3 = AnneeScolaire.objects.create(nom='2021-2022')
    annee_4 = AnneeScolaire.objects.create(nom='2020-2021')
    annee_5 = AnneeScolaire.objects.create(nom='2019-2020')

    # Matière
    matiere = Matiere.objects.create(nom='Mathématiques', coefficient=4)
    matiere_1 = Matiere.objects.create(nom='Algorithmique et programmation', coefficient=4)
    matiere_2 = Matiere.objects.create(nom='Architecture des ordinateurs', coefficient=3)
    matiere_3 = Matiere.objects.create(nom='Systèmes d’exploitation', coefficient=2)
    matiere_4 = Matiere.objects.create(nom='Anglais technique', coefficient=1)
    matiere_5 = Matiere.objects.create(nom='Structures de données avancées', coefficient=4)
    matiere_6 = Matiere.objects.create(nom='Programmation orientée objet', coefficient=3)
    matiere_7 = Matiere.objects.create(nom='Réseaux informatiques', coefficient=3)
    matiere_8 = Matiere.objects.create(nom='Sécurité informatique', coefficient=3)
    matiere_9 = Matiere.objects.create(nom='Intelligence artificielle - Introduction', coefficient=3)
    matiere_10 = Matiere.objects.create(nom='Cloud computing', coefficient=2)
    matiere_11 = Matiere.objects.create(nom='Algèbre Matriciel', coefficient=2)

    matiere.profs.add(prof)
    matiere_11.profs.add(prof)
    matiere_1.profs.add(prof_1)
    matiere_2.profs.add(prof_2)
    matiere_3.profs.add(prof_2)
    matiere_4.profs.add(prof_4)
    matiere_5.profs.add(prof_5)
    matiere_6.profs.add(prof_1)
    matiere_7.profs.add(prof_3)
    matiere_8.profs.add(prof_3)
    matiere_9.profs.add(prof_6)
    matiere_10.profs.add(prof_6)


    # Inscription
    inscription = Inscription.objects.create(etudiant=etudiant, classe=classe_3, annee=annee)
    inscription_10 = Inscription.objects.create(etudiant=etudiant, classe=classe, annee=annee_2)
    inscription_1 = Inscription.objects.create(etudiant=etudiant_1, classe=classe_2, annee=annee_1)
    inscription_2 = Inscription.objects.create(etudiant=etudiant_2, classe=classe, annee=annee)
    inscription_3 = Inscription.objects.create(etudiant=etudiant_3, classe=classe, annee=annee_1)
    inscription_4 = Inscription.objects.create(etudiant=etudiant_4, classe=classe, annee=annee)
    inscription_5 = Inscription.objects.create(etudiant=etudiant_5, classe=classe_2, annee=annee_2)
    inscription_6 = Inscription.objects.create(etudiant=etudiant_6, classe=classe, annee=annee)
    inscription_7 = Inscription.objects.create(etudiant=etudiant_7, classe=classe_4, annee=annee_5)
    inscription_8 = Inscription.objects.create(etudiant=etudiant_8, classe=classe_3, annee=annee_4)
    inscription_9 = Inscription.objects.create(etudiant=etudiant_9, classe=classe_5, annee=annee)



    # Type de note
    type_note = Type.objects.create(nom='Examen', pourcentage=60)
    type_note_2 = Type.objects.create(nom='Controle Continu', pourcentage=40)

    # Note
    Note.objects.create(
        inscription=inscription, matiere=matiere, type=type_note, note='15.5',
        commentaire='Bien', date_eval=timezone.now() - timedelta(days=2)
    )
    Note.objects.create(
        inscription=inscription, matiere=matiere, type=type_note_2, note='10',
        commentaire='Passable', date_eval=timezone.now() - timedelta(days=15)
    )
    Note.objects.create(
        inscription=inscription, matiere=matiere, type=type_note_2, note='03',
        commentaire='Mauvais, dois se ressaisir', date_eval=timezone.now() - timedelta(days=30)
    )

    Note.objects.create(inscription=inscription, matiere=matiere_2, type=type_note, note='15.5', commentaire='Bien', date_eval=timezone.now() - timedelta(days=2))
    Note.objects.create(inscription=inscription, matiere=matiere_2, type=type_note_2, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_3, type=type_note, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_3, type=type_note_2, note='03', commentaire='Mauvais, dois se ressaisir', date_eval=timezone.now() - timedelta(days=30))
    Note.objects.create(inscription=inscription, matiere=matiere_4, type=type_note, note='17', commentaire='Bien', date_eval=timezone.now() - timedelta(days=2))
    Note.objects.create(inscription=inscription, matiere=matiere_4, type=type_note_2, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_5, type=type_note, note='14', commentaire='Bien', date_eval=timezone.now() - timedelta(days=2))
    Note.objects.create(inscription=inscription, matiere=matiere_5, type=type_note_2, note='9.5', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_6, type=type_note_2, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_6, type=type_note, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_7, type=type_note_2, note='01', commentaire='Mauvais, dois se ressaisir', date_eval=timezone.now() - timedelta(days=30))
    Note.objects.create(inscription=inscription, matiere=matiere_7, type=type_note, note='18', commentaire='Très Bien', date_eval=timezone.now() - timedelta(days=2))
    Note.objects.create(inscription=inscription, matiere=matiere_8, type=type_note_2, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription, matiere=matiere_8, type=type_note, note='14', commentaire='Bien', date_eval=timezone.now() - timedelta(days=2))
    Note.objects.create(inscription=inscription_10, matiere=matiere_10, type=type_note_2, note='10', commentaire='Passable', date_eval=timezone.now() - timedelta(days=15))
    Note.objects.create(inscription=inscription_10, matiere=matiere_10, type=type_note, note='14', commentaire='Bien', date_eval=timezone.now() - timedelta(days=2))

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
